// SEO-optimized blog content
export const BLOG_POSTS = [
  {
    slug: "how-to-spot-ai-generated-resume",
    title: "How to Spot an AI-Generated Resume in 2024",
    excerpt: "Learn the telltale signs that a resume was written by ChatGPT. Recruiters share their secrets for detecting AI-generated job applications.",
    author: "The Team",
    date: "2024-12-01",
    readTime: "7 min",
    category: "Guides",
    featured: true,
    keywords: ["AI resume detection", "ChatGPT resume", "ATS"],
  },
  {
    slug: "dead-internet-theory-explained",
    title: "Dead Internet Theory: Is Everyone Online Actually a Bot?",
    excerpt: "Dead Internet Theory suggests most online content is AI-generated. We examine the evidence and what it means for human connection.",
    author: "The Team",
    date: "2024-11-28",
    readTime: "10 min",
    category: "Deep Dives",
    featured: true,
    keywords: ["dead internet theory", "bots online", "AI content"],
  },
  {
    slug: "ats-systems-how-they-work",
    title: "How ATS Systems Work: Why Your Resume Gets Rejected",
    excerpt: "75% of resumes are rejected by ATS before humans see them. Learn how Applicant Tracking Systems work and how to optimize.",
    author: "The Team",
    date: "2024-11-20",
    readTime: "8 min",
    category: "Career",
    featured: false,
    keywords: ["ATS system", "applicant tracking", "resume optimization"],
  },
  {
    slug: "fake-dating-profiles-how-to-spot",
    title: "How to Spot Fake Dating Profiles: AI Catfish Detection",
    excerpt: "Up to 20% of dating profiles are fake. Learn to identify AI-generated photos and ChatGPT bios to protect yourself.",
    author: "The Team",
    date: "2024-11-15",
    readTime: "9 min",
    category: "Guides",
    featured: false,
    keywords: ["fake dating profile", "catfish detection", "romance scam"],
  },
  {
    slug: "ai-detection-tools-compared",
    title: "AI Detection Tools Compared: Which Actually Work?",
    excerpt: "We tested GPTZero, Originality.ai, and others against AI content. See which detectors work and which fail.",
    author: "The Team",
    date: "2024-11-10",
    readTime: "12 min",
    category: "Reviews",
    featured: false,
    keywords: ["AI detection tools", "GPTZero review", "ChatGPT detector"],
  },
];

export const BLOG_CONTENT: Record<string, string> = {
  "how-to-spot-ai-generated-resume": `
<h2>The 7 Tell-Tale Signs of an AI-Generated Resume</h2>

<p>According to a 2024 ResumeBuilder survey, <strong>46% of job seekers</strong> now use ChatGPT to write resumes. Here's what recruiters look for.</p>

<h3>1. Suspiciously Perfect Grammar</h3>
<p>Human writing has natural imperfections. AI content is grammatically flawless to the point of feeling sterile.</p>

<h3>2. Buzzword Overload</h3>
<p>"Leveraged cross-functional synergies to optimize operational efficiency." If it sounds like corporate bingo, it's likely AI.</p>

<h3>3. Vague, Round-Number Achievements</h3>
<p>AI loves "Improved efficiency by 30%" or "Increased sales by 50%." Real achievements are messier: "Reduced response time from 4.2 hours to 47 minutes."</p>

<h3>4. Missing Specificity</h3>
<p>AI can't know your company's proprietary software, specific clients, or internal project names.</p>

<h3>5. Uniform Tone Across Different Roles</h3>
<p>Real career progression shows evolution in how we describe work. AI maintains eerily consistent voice.</p>

<h3>6. Generic Soft Skills</h3>
<p>"Excellent communication skills" is an AI favorite. Humans demonstrate through examples.</p>

<h3>7. Perfect Keyword Optimization</h3>
<p>If the resume hits every job description keyword, it was probably engineered by AI.</p>

<h2>How to Humanize Your Resume</h2>
<ol>
<li><strong>Add specific details</strong> — Real project names, actual metrics</li>
<li><strong>Include your voice</strong> — Keep quirky descriptions</li>
<li><strong>Vary sentence structure</strong> — Mix punchy bullets with explanations</li>
<li><strong>Reference unique context</strong> — Things only you'd know</li>
</ol>

<p>Not sure if your resume passes? <a href="/services/resume">Our Resume Sanitizer</a> analyzes for AI patterns and helps humanize it.</p>
`,

  "dead-internet-theory-explained": `
<h2>What is Dead Internet Theory?</h2>

<p>Dead Internet Theory claims most online content and interactions are AI-generated, with only a small percentage from real humans.</p>

<h2>The Statistics</h2>
<ul>
<li><strong>47.4%</strong> of internet traffic comes from bots (Imperva 2022)</li>
<li><strong>5.8 billion</strong> fake accounts removed by Facebook in 2022</li>
<li><strong>Twitter/X</strong> estimates 5-20% of accounts are bots</li>
<li><strong>90%</strong> of online content could be AI-generated by 2026 (Europol)</li>
</ul>

<h2>What the Theory Gets Right</h2>
<p>Bot farms are real. AI content is exploding. Authenticity is increasingly rare. The signal-to-noise ratio has shifted dramatically since ChatGPT's release.</p>

<h2>What It Gets Wrong</h2>
<p>Billions of real humans still use the internet. Bot traffic includes scrapers and crawlers, not just fake engagement. Confirmation bias makes everything seem suspicious.</p>

<h2>The Psychological Impact</h2>
<p>When you can't trust interactions are genuine, online engagement feels hollow, trust erodes, and human connection becomes harder.</p>

<p>The solution isn't to unplug—it's to build better verification tools. <a href="/game">Test your detection skills</a> in our Real vs AI game.</p>
`,

  "ats-systems-how-they-work": `
<h2>What Is an ATS?</h2>
<p>An Applicant Tracking System manages job applications. It parses resumes, matches keywords, ranks candidates, and filters applications. <strong>75% of resumes are rejected before humans see them.</strong></p>

<h2>Why Your Resume Gets Rejected</h2>
<ol>
<li><strong>Wrong file format</strong> — Some ATS can't read PDFs properly</li>
<li><strong>Complex formatting</strong> — Tables, columns, graphics confuse parsers</li>
<li><strong>Missing keywords</strong> — Exact phrase matching matters</li>
<li><strong>Non-standard headers</strong> — Use "Experience" not "Where I've Worked"</li>
<li><strong>Keyword stuffing</strong> — Trying too hard triggers spam filters</li>
<li><strong>No exact requirement match</strong> — 4.5 years ≠ 5 years required</li>
</ol>

<h2>How to Beat ATS</h2>
<ul>
<li>Use standard section headers</li>
<li>Stick to single-column layouts</li>
<li>Mirror job description language</li>
<li>Include both acronyms and spelled-out terms</li>
<li>Quantify achievements with specific numbers</li>
</ul>

<h2>The AI Detection Problem</h2>
<p>Many companies now use AI detection alongside ATS. You need to optimize for algorithms while appearing human. Our <a href="/services/resume">Resume Sanitizer</a> helps you find this balance.</p>
`,

  "fake-dating-profiles-how-to-spot": `
<h2>The Scale of the Problem</h2>
<p>Up to <strong>20% of profiles on major dating apps</strong> are fake—bots, scammers, or catfish using AI-generated content.</p>

<h2>Red Flags in Photos</h2>
<h3>AI-Generated Image Signs</h3>
<ul>
<li><strong>Perfect symmetry</strong> — Human faces are naturally asymmetrical</li>
<li><strong>Weird backgrounds</strong> — Warped lines, impossible architecture</li>
<li><strong>Hair anomalies</strong> — Strands merging into nothing</li>
<li><strong>Teeth problems</strong> — Too many teeth, merged teeth</li>
<li><strong>Jewelry glitches</strong> — Earrings that don't match, fading necklaces</li>
</ul>

<h2>Red Flags in Bios</h2>
<ul>
<li>"Looking for something real" / "seeking authentic connection"</li>
<li>Generic interests: "travel, food, music, Netflix"</li>
<li>Perfect grammar, no personality</li>
<li>Vague job and location details</li>
</ul>

<h2>How to Verify</h2>
<ol>
<li><strong>Reverse image search</strong> — Google Images, TinEye</li>
<li><strong>Request specific photos</strong> — "Send pic holding 3 fingers"</li>
<li><strong>Video call</strong> — Bots can't do real-time video</li>
<li><strong>Ask local questions</strong> — Restaurants, events, weather</li>
</ol>

<p>Want to verify a suspicious profile? Our <a href="/services/profile">Fake Profile Spotter</a> analyzes photos for AI artifacts and bios for bot patterns.</p>
`,

  "ai-detection-tools-compared": `
<h2>The Tools We Tested</h2>
<p>We tested GPTZero, Originality.ai, Copyleaks, ZeroGPT, Turnitin, and Winston AI against 50 documents.</p>

<h2>Results Summary</h2>
<table>
<tr><th>Tool</th><th>Accuracy</th><th>Verdict</th></tr>
<tr><td>Originality.ai</td><td>82%</td><td>Best overall, worth the price</td></tr>
<tr><td>Winston AI</td><td>79%</td><td>Solid newer option</td></tr>
<tr><td>Copyleaks</td><td>78%</td><td>Good but prone to false positives</td></tr>
<tr><td>Turnitin</td><td>76%</td><td>Conservative, best for academics</td></tr>
<tr><td>GPTZero</td><td>74%</td><td>Decent for obvious cases</td></tr>
<tr><td>ZeroGPT</td><td>61%</td><td>Not recommended</td></tr>
</table>

<h2>The Uncomfortable Truth</h2>
<p>No AI detector is reliable for high-stakes decisions:</p>
<ul>
<li>AI writing keeps improving—detectors play catch-up</li>
<li>Simple paraphrasing defeats most detectors</li>
<li>False positives have wrongly accused students</li>
<li>Detectors may be biased against certain writing styles</li>
</ul>

<h2>What Actually Works</h2>
<p>Instead of relying on detectors alone: conduct interviews, request process evidence (drafts, notes), and look for knowledge that requires firsthand experience.</p>

<p>Need human-verified content? Our tools focus on helping you create authentically human work from the start.</p>
`,
};
