import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowLeft, Calendar, Clock, Share2, Twitter, Linkedin } from "lucide-react";
import { notFound } from "next/navigation";

// This would come from a CMS or MDX in production
const BLOG_CONTENT: Record<string, { title: string; content: string; date: string; readTime: string; category: string }> = {
  "how-to-spot-ai-generated-resume": {
    title: "How to Spot an AI-Generated Resume in 2024",
    date: "2024-12-01",
    readTime: "5 min",
    category: "Guides",
    content: `
# How to Spot an AI-Generated Resume in 2024

The age of AI-assisted job applications is here, and recruiters are catching on. Here's what they're looking for when they suspect a resume has been written by ChatGPT.

## The Tell-Tale Signs

### 1. Perfect Grammar, Zero Personality
AI-generated resumes are technically flawless but emotionally flat. They lack the small imperfections that make writing feel human.

### 2. Buzzword Overload
"Leveraged synergies to drive cross-functional initiatives" — if every bullet point sounds like a LinkedIn influencer, it's probably AI.

### 3. Generic Achievements
"Improved efficiency by 30%" without context or specifics. AI loves round numbers and vague improvements.

### 4. Consistent Voice Throughout
Real humans write differently when describing different experiences. AI maintains an eerily consistent tone.

## How to Fix Your AI-Assisted Resume

1. **Add specific details** — Real projects, real numbers, real context
2. **Include your voice** — Throw in a conversational phrase or two
3. **Vary your sentence structure** — Mix short punchy lines with longer explanations
4. **Reference specific technologies, people, or events** — Things AI wouldn't know

## The Bottom Line

AI can be a great starting point, but the final product needs to feel human. That's where we come in.

---

*Want to check if your resume passes the human test? Try our [Resume Sanitizer](/services/resume).*
    `,
  },
  "dead-internet-theory-explained": {
    title: "Dead Internet Theory: Is Everyone Online Actually a Bot?",
    date: "2024-11-28",
    readTime: "8 min",
    category: "Deep Dives",
    content: `
# Dead Internet Theory: Is Everyone Online Actually a Bot?

The conspiracy theory that won't die — mostly because its believers aren't sure if anyone arguing against it is real.

## What is Dead Internet Theory?

The Dead Internet Theory suggests that most online content and interactions are generated by AI and bots, and that the "real" internet died sometime around 2016-2017.

Sounds crazy? Let's look at the evidence.

## The Uncomfortable Statistics

- **47%** of all internet traffic comes from bots (Imperva, 2023)
- **Facebook** removed 5.8 billion fake accounts in 2022
- **Twitter/X** estimates 5% of users are bots (Elon Musk claims it's higher)
- AI can now generate indistinguishable text, images, and videos

## The Psychological Impact

When you can't trust that anyone online is real:
- Engagement becomes meaningless
- Trust erodes across platforms
- Authentic voices get drowned out
- Human connection feels impossible

## Our Take

Is the internet "dead"? No. But it's definitely on life support.

The solution isn't to unplug — it's to build better tools for verification. That's why we exist.

---

*Worried about the bots? [Test your detection skills](/game) in our Real vs AI game.*
    `,
  },
};

export async function generateStaticParams() {
  return Object.keys(BLOG_CONTENT).map((slug) => ({ slug }));
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = BLOG_CONTENT[slug];

  if (!post) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-black">
      <article className="max-w-3xl mx-auto px-6 py-32">
        <Link href="/blog">
          <Button variant="ghost" className="gap-2 pl-0 mb-8 hover:bg-transparent hover:text-accent">
            <ArrowLeft className="w-4 h-4" /> Back to Blog
          </Button>
        </Link>

        {/* Header */}
        <header className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <span className="px-2 py-1 text-xs font-mono bg-accent/10 text-accent rounded">
              {post.category}
            </span>
            <span className="text-xs text-gray-500 flex items-center gap-1">
              <Calendar className="w-3 h-3" /> {post.date}
            </span>
            <span className="text-xs text-gray-500 flex items-center gap-1">
              <Clock className="w-3 h-3" /> {post.readTime}
            </span>
          </div>
          
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-6">
            {post.title}
          </h1>

          {/* Share buttons */}
          <div className="flex items-center gap-3">
            <span className="text-xs text-gray-500">Share:</span>
            <a 
              href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(`https://notarobot.com/blog/${slug}`)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 rounded-lg border border-zinc-800 hover:border-zinc-700 hover:text-accent transition-colors"
              aria-label="Share on Twitter"
            >
              <Twitter className="w-4 h-4" />
            </a>
            <a 
              href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(`https://notarobot.com/blog/${slug}`)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 rounded-lg border border-zinc-800 hover:border-zinc-700 hover:text-accent transition-colors"
              aria-label="Share on LinkedIn"
            >
              <Linkedin className="w-4 h-4" />
            </a>
          </div>
        </header>

        {/* Content */}
        <div className="prose prose-invert prose-lg max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-accent prose-a:no-underline hover:prose-a:underline prose-code:text-accent prose-pre:bg-zinc-900 prose-pre:border prose-pre:border-zinc-800">
          <div dangerouslySetInnerHTML={{ __html: post.content.replace(/\n/g, '<br />') }} />
        </div>

        {/* CTA */}
        <div className="mt-16 p-8 rounded-2xl border border-zinc-800 bg-zinc-900/50 text-center">
          <h3 className="text-xl font-bold mb-2">Ready to verify your humanity?</h3>
          <p className="text-gray-400 mb-6">Try our tools and join the resistance against the machines.</p>
          <div className="flex gap-4 justify-center">
            <Link href="/game">
              <Button className="bg-accent text-black hover:bg-accent/90">Play Real vs AI</Button>
            </Link>
            <Link href="/services/resume">
              <Button variant="outline">Sanitize Resume</Button>
            </Link>
          </div>
        </div>
      </article>
    </main>
  );
}
